"""
Test that the context field is generated by the ReasonerLLM
TICKET-001: V3 format with structured context object
"""
import unittest

from janus.ai.reasoning.reasoner_llm import ReasonerLLM


class TestContextField(unittest.TestCase):
    """Test context field in structured plans - V3 Format"""

    def setUp(self):
        """Initialize with mock backend"""
        self.reasoner = ReasonerLLM(backend="mock")

    def test_context_field_present(self):
        """Test that context field is present in generated steps"""
        plan = self.reasoner.generate_structured_plan("Ouvre Safari et va sur YouTube", language="fr")

        # Verify steps have context field
        self.assertIn("steps", plan)
        for step in plan["steps"]:
            self.assertIn("context", step, f"Step {step} missing context field")
            
            # V3: context should be a dict with required fields
            self.assertIsInstance(step["context"], dict, "Context must be a dict in V3 format")
            
            # Check all V3 context fields exist
            for field in ["app", "surface", "url", "domain", "thread", "record"]:
                self.assertIn(field, step["context"], f"Context missing required field: {field}")

    def test_context_null_values_for_app_open(self):
        """Test that context has null values for app opening in V3"""
        plan = self.reasoner.generate_structured_plan("Ouvre Safari", language="fr")

        first_step = plan["steps"][0]
        context = first_step.get("context")
        
        # V3: context is a dict, not None
        self.assertIsInstance(context, dict)
        
        # All fields should be None for initial app open
        for field in ["app", "surface", "url", "domain", "thread", "record"]:
            self.assertIsNone(context.get(field), f"Field {field} should be None for initial app open")

    def test_context_propagation(self):
        """Test that context propagates between steps in V3 format"""
        plan = self.reasoner.generate_structured_plan(
            "Ouvre Safari, va sur YouTube et cherche Python", language="fr"
        )

        # Step 1: open Safari -> context: all fields None
        # Step 2: open youtube.com -> context.app = "Safari", domain = "youtube.com"
        # Step 3: search -> context propagates from step 2

        self.assertEqual(len(plan["steps"]), 3, f"Expected 3 steps, got {len(plan['steps'])}")
        
        # Step 1: Initial app open - all None
        step1_ctx = plan["steps"][0]["context"]
        self.assertIsNone(step1_ctx["app"])
        self.assertIsNone(step1_ctx["surface"])
        self.assertIsNone(step1_ctx["domain"])
        
        # Step 2: Navigate to YouTube - app and domain populated
        step2_ctx = plan["steps"][1]["context"]
        self.assertEqual(step2_ctx["app"], "Safari")
        self.assertEqual(step2_ctx["domain"], "youtube.com")
        self.assertEqual(step2_ctx["surface"], "browser")
        
        # Step 3: Search - context propagated from step 2
        step3_ctx = plan["steps"][2]["context"]
        self.assertEqual(step3_ctx["app"], "Safari")
        self.assertEqual(step3_ctx["domain"], "youtube.com")
        self.assertEqual(step3_ctx["surface"], "browser")

    def test_context_for_system_actions(self):
        """Test that system actions have all-null context in V3"""
        plan = self.reasoner.generate_structured_plan("Copie le texte", language="fr")

        self.assertIn("steps", plan)
        self.assertGreater(len(plan["steps"]), 0)
        
        context = plan["steps"][0].get("context")
        self.assertIsInstance(context, dict)
        
        # All fields should be None for system action
        for field in ["app", "surface", "url", "domain", "thread", "record"]:
            self.assertIsNone(context.get(field))

    def test_context_for_chrome_actions(self):
        """Test that Chrome-specific actions have Chrome context in V3"""
        plan = self.reasoner.generate_structured_plan("Ouvre Chrome et résume la page", language="fr")

        self.assertIn("steps", plan)
        # Should have at least extract_text with chrome context
        chrome_steps = [s for s in plan["steps"] if s.get("action") in ["extract_text", "extract_page_text"]]
        if chrome_steps:
            context = chrome_steps[0].get("context")
            self.assertIsInstance(context, dict)
            self.assertEqual(context.get("app"), "Chrome")

    def test_fallback_includes_v3_context(self):
        """Test that fallback plan generation includes V3 context structure"""
        # Create unavailable LLM to trigger fallback
        llm = ReasonerLLM(backend="llama-cpp", model_path="/nonexistent/model.gguf")
        self.assertFalse(llm.available)

        plan = llm.generate_structured_plan("Ouvre Chrome", language="fr")

        self.assertIn("steps", plan)
        for step in plan["steps"]:
            self.assertIn("context", step, f"Fallback step {step} missing context field")
            context = step["context"]
            self.assertIsInstance(context, dict, "V3 context must be a dict")
            
            # Check all V3 fields exist
            for field in ["app", "surface", "url", "domain", "thread", "record"]:
                self.assertIn(field, context, f"V3 context missing field: {field}")

    def test_english_command_v3_context(self):
        """Test that English commands also generate V3 context structure"""
        plan = self.reasoner.generate_structured_plan("Open Safari", language="en")

        self.assertIn("steps", plan)
        for step in plan["steps"]:
            self.assertIn("context", step, f"English command step {step} missing context field")
            context = step["context"]
            self.assertIsInstance(context, dict, "V3 context must be a dict")
            
            # Check all V3 fields
            for field in ["app", "surface", "url", "domain", "thread", "record"]:
                self.assertIn(field, context, f"V3 context missing field: {field}")


if __name__ == "__main__":
    unittest.main()
